apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: health-check-example-foje
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: health-check-example-foje
    app.kubernetes.io/part-of: snowdrop
  name: health-check-example-foje
  namespace: cmoullia-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: health-check-example-foje
status:
  loadBalancer: {}
